import {
  BookOpen,
  Bot,
  ClipboardList,
  Factory,
  FileOutput,
  FolderCheck,
  LayoutDashboard,
  PackageSearch,
  Settings2,
} from "lucide-react";

import type { AppDefinition } from "../types";

/**
 * 内置应用配置 —— 应用中心的唯一数据源。
 *
 * licenseModule 字段对应 useLicense.hasModule(name) 的入参；
 * 为 null 表示始终可见（无需 license）。
 * 与 Sidebar.tsx 的 allNavItems 保持一致。
 */
export const BUILTIN_APPS: AppDefinition[] = [
  {
    id: "dashboard",
    name: "工作台",
    description: "待办聚合与项目进度概览，开启高效的一天",
    icon: LayoutDashboard,
    businessDomain: "universal",
    stageTag: "overview",
    path: "/dashboard",
    licenseModule: null,
    sortOrder: 1,
    sortKey: "gongzuotai",
    isBuiltin: true,
  },
  {
    id: "smart-writing",
    name: "智能写作",
    description: "AI 辅助写作，从提纲到终稿全流程智能生成",
    icon: Bot,
    businessDomain: "universal",
    stageTag: "process",
    path: "/writing",
    licenseModule: null,
    sortOrder: 2,
    sortKey: "zhinengxiezuo",
    isBuiltin: true,
  },
  {
    id: "projects",
    name: "报告项目",
    description: "管理报告项目全生命周期，章节分配与审批跟踪",
    icon: ClipboardList,
    businessDomain: "报告编撰",
    stageTag: "collaborate",
    path: "/projects",
    licenseModule: "project",
    sortOrder: 3,
    sortKey: "baogaoxiangmu",
    isBuiltin: true,
  },
  {
    id: "docmgr",
    name: "文档空间",
    description: "团队文档协作中心，多人实时编辑与版本管理",
    icon: FolderCheck,
    businessDomain: "universal",
    stageTag: "collaborate",
    path: "/docmgr",
    licenseModule: "docmgr",
    sortOrder: 4,
    sortKey: "wendangkongjian",
    isBuiltin: true,
  },
  {
    id: "knowledge-factory",
    name: "知识工厂",
    description: "结构化知识生产流水线，从原始资料到可用知识库",
    icon: Factory,
    businessDomain: "知识管理",
    stageTag: "process",
    path: "/knowledge-factory",
    licenseModule: "knowledge",
    sortOrder: 5,
    sortKey: "zhishigongchang",
    isBuiltin: true,
  },
  {
    id: "knowledge",
    name: "知识库",
    description: "检索企业知识资产，RAG 增强问答与智能引用",
    icon: BookOpen,
    businessDomain: "知识管理",
    stageTag: "retrieve",
    path: "/knowledge",
    licenseModule: "knowledge",
    sortOrder: 6,
    sortKey: "zhishiku",
    isBuiltin: true,
  },
  {
    id: "output",
    name: "报告输出",
    description: "一键生成多格式报告成果，模板化排版与导出",
    icon: FileOutput,
    businessDomain: "报告编撰",
    stageTag: "output",
    path: "/output",
    licenseModule: "report",
    sortOrder: 7,
    sortKey: "baogaochushu",
    isBuiltin: true,
  },
  {
    id: "procurement",
    name: "采购管理",
    description: "合同价格分析与采购分项管理，聚类归并与统计",
    icon: PackageSearch,
    businessDomain: "采购管理",
    stageTag: "process",
    path: "/contract-price",
    licenseModule: null,
    sortOrder: 8,
    sortKey: "caigouguanli",
    isBuiltin: true,
  },
  {
    id: "admin",
    name: "系统管理",
    description: "用户、角色、部门与权限的统一管理后台",
    icon: Settings2,
    businessDomain: "admin",
    stageTag: "manage",
    path: "/admin",
    licenseModule: null,
    adminOnly: true,
    sortOrder: 9,
    sortKey: "xitongguanli",
    isBuiltin: true,
  },
];
