#!/usr/bin/env bash
# generate-config.sh — 读 deploy.conf（唯一可信配置源），生成 config.yaml / .env / extensions_config.json
#
# 设计：deploy.conf 是运维手写的 KEY=VALUE 文件。本脚本做**安全的逐行解析**
# （不 `source`，避免含空格/特殊字符的值如 BRAND_FOOTER 触发 shell 解析错误），
# 并自动填入可推导的默认值（DB 密码等）。不可猜的值（secret/origin/root）由调用方传入。
#
# Usage: generate-config.sh --conf <deploy.conf> --out <dir> --root <abs path> --secret <str> --origin <url>
set -euo pipefail

CONF=""; OUT="."; ROOT=""; SECRET=""; ORIGIN=""
while [ $# -gt 0 ]; do
  case "$1" in
    --conf)   CONF="$2"; shift 2;;
    --out)    OUT="$2";  shift 2;;
    --root)   ROOT="$2"; shift 2;;
    --secret) SECRET="$2"; shift 2;;
    --origin) ORIGIN="$2"; shift 2;;
    -h|--help) echo "Usage: $0 --conf <deploy.conf> --out <dir> --root <abs> --secret <str> --origin <url>"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 1;;
  esac
done
[ -n "${CONF:-}" ] && [ -f "$CONF" ] || { echo "ERR: --conf <file> required" >&2; exit 1; }
mkdir -p "$OUT"

# ── 安全解析 conf：逐行读 KEY=VALUE，去引号/空白，export 到当前 shell ──
# 不用 source：避免 `BRAND_FOOTER=© 2026 X` 这种带空格的值被当命令执行。
parse_conf() {
  local line key val
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in ''|\#*) continue;; esac        # 跳过空行 / # 开头的注释
    [[ "$line" != *=* ]] && continue               # 无 = 的行跳过
    key="${line%%=*}"
    val="${line#*=}"
    key="$(echo "$key" | tr -d '[:space:]')"        # key 不应有空格
    val="${val#\"}"; val="${val%\"}"                # 去首尾双引号
    val="${val#\'}"; val="${val%\'}"                # 去首尾单引号
    [ -n "$key" ] && export "${key}=${val}"
  done < "$1"
}
parse_conf "$CONF"

BRAND_NAME="${BRAND_NAME:-EAIFlow}"
LLM_BASE_URL="${LLM_BASE_URL:-}"
LLM_API_KEY="${LLM_API_KEY:-}"
LLM_MODEL="${LLM_MODEL:-}"
RAGFLOW_API_KEY="${RAGFLOW_API_KEY:-}"
RAGFLOW_HTTP_PROXY="${RAGFLOW_HTTP_PROXY:-}"
DB_PASSWORD="${DB_PASSWORD:-agentflow123}"

# ── .env ──
cat > "$OUT/.env" <<EOF
# Generated by generate-config.sh — 勿手改；改 deploy.conf 后重新生成。
DEER_FLOW_ROOT=${ROOT}
BETTER_AUTH_SECRET=${SECRET}
HOME=/root
PORT=4026
# F.2: gateway 必须用 Docker 服务名连库，否则容器内 localhost 不通。
EXTENSIONS_DB_HOST=postgres-ext
EXTENSIONS_DB_PORT=5432
EXTENSIONS_DB_USER=agentflow
EXTENSIONS_DB_PASSWORD=${DB_PASSWORD}
EXTENSIONS_DB_NAME=agentflow
POSTGRES_EXT_PASSWORD=${DB_PASSWORD}
# F.6: compose 已硬编码网络名，NETWORK_NAME 仅供文档参考，勿取消注释。
DEER_FLOW_TRUSTED_ORIGINS=${ORIGIN}
RAGFLOW_API_KEY=${RAGFLOW_API_KEY}
RAGFLOW_HTTP_PROXY=${RAGFLOW_HTTP_PROXY}
EOF
# 追加可选云端 API key（若 conf 提供）。
for k in AGNES_API_KEY ZHIPU_API_KEY DEEPSEEK_API_KEY SILICONFLOW_API_KEY INTERNAL_LLM_API_KEY; do
  v="${!k:-}"
  [ -n "$v" ] && echo "${k}=${v}" >> "$OUT/.env"
done

# ── config.yaml ──
if [ -n "$LLM_BASE_URL" ]; then
cat > "$OUT/config.yaml" <<EOF
models:
  - name: intranet-llm
    display_name: 内网大模型
    use: langchain_openai:ChatOpenAI
    model: ${LLM_MODEL}
    api_key: ${LLM_API_KEY}
    base_url: ${LLM_BASE_URL}
    request_timeout: 600.0
    max_retries: 2
    max_tokens: 8192
    temperature: 0.7
    supports_vision: false
    supports_thinking: false
EOF
else
  # 未配内网 LLM：内网可连外网则自行配置云端模型，或手填 models 段。
  echo "# LLM_BASE_URL 未设置；请配置 models 段（内网 LLM 或可连的云端模型）。" > "$OUT/config.yaml"
fi

# ── extensions_config.json ──
cat > "$OUT/extensions_config.json" <<'EOF'
{"mcpServers": {}, "skills": {}}
EOF

echo "Generated: $OUT/{.env,config.yaml,extensions_config.json} (brand=${BRAND_NAME})"
