#!/usr/bin/env bash
# generate-config.sh — 读 deploy.conf（唯一可信配置源），生成 config.yaml / .env / extensions_config.json
#
# 设计：deploy.conf 是运维手写的 KEY=VALUE 文件。本脚本做**安全的逐行解析**
# （不 `source`，避免含空格/特殊字符的值如 BRAND_FOOTER 触发 shell 解析错误），
# 并自动填入可推导的默认值（DB 密码等）。不可猜的值（secret/origin/root）由调用方传入。
#
# Usage: generate-config.sh --conf <deploy.conf> --out <dir> --root <abs path> --secret <str> --origin <url>
set -euo pipefail

CONF=""; OUT="."; ROOT=""; SECRET=""; ORIGIN=""
while [ $# -gt 0 ]; do
  case "$1" in
    --conf)   CONF="$2"; shift 2;;
    --out)    OUT="$2";  shift 2;;
    --root)   ROOT="$2"; shift 2;;
    --secret) SECRET="$2"; shift 2;;
    --origin) ORIGIN="$2"; shift 2;;
    -h|--help) echo "Usage: $0 --conf <deploy.conf> --out <dir> --root <abs> --secret <str> --origin <url>"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 1;;
  esac
done
[ -n "${CONF:-}" ] && [ -f "$CONF" ] || { echo "ERR: --conf <file> required" >&2; exit 1; }
mkdir -p "$OUT"

# EAI-CUSTOM: 检测可用 Python 3（config.yaml 注入内网 LLM 用；Windows 上 python3 常是 Store 占位符）
PYTHON=""
for c in python3 python; do
  if command -v "$c" >/dev/null 2>&1 && "$c" -c 'import sys; assert sys.version_info >= (3,)' 2>/dev/null; then
    PYTHON="$c"; break
  fi
done

# ── 安全解析 conf：逐行读 KEY=VALUE，去引号/空白，export 到当前 shell ──
# 不用 source：避免 `BRAND_FOOTER=© 2026 X` 这种带空格的值被当命令执行。
parse_conf() {
  local line key val
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in ''|\#*) continue;; esac        # 跳过空行 / # 开头的注释
    [[ "$line" != *=* ]] && continue               # 无 = 的行跳过
    key="${line%%=*}"
    val="${line#*=}"
    key="$(echo "$key" | tr -d '[:space:]')"        # key 不应有空格
    val="${val#\"}"; val="${val%\"}"                # 去首尾双引号
    val="${val#\'}"; val="${val%\'}"                # 去首尾单引号
    val="$(echo "$val" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"  # 去首尾空白（防 trailing space 污染空值判断）
    [ -n "$key" ] && export "${key}=${val}"
  done < "$1"
}
parse_conf "$CONF"

BRAND_NAME="${BRAND_NAME:-EAIFlow}"
LLM_BASE_URL="${LLM_BASE_URL:-}"
LLM_API_KEY="${LLM_API_KEY:-}"
LLM_MODEL="${LLM_MODEL:-}"
RAGFLOW_API_KEY="${RAGFLOW_API_KEY:-}"
RAGFLOW_HTTP_PROXY="${RAGFLOW_HTTP_PROXY:-}"
DB_PASSWORD="${DB_PASSWORD:-agentflow123}"

# ── .env：保留 shipped 完整文件为基底，只定向注入 deploy.conf 推导的键 ──
# EAI-CUSTOM: 旧实现用 `cat >` 覆盖，把 offline-export 拷入的完整 .env（含端口映射/
# 服务名/workers/RAGFlow 端口等 50+ 键）抹成 15 行最小模板 → 部署后大量功能失效
# （buglog bug-1015）。改为：shipped .env 存在则定向 patch 环境专属键，不存在才写最小集。
BASE_ENV="$OUT/.env"
# 幂等键值注入：键存在则改值，不存在则追加。用 `|` 做 sed 分隔符，兼容含 / 的路径/URL/密钥。
set_env_kv() {  # set_env_kv <KEY> <VALUE>
  local k="$1" v="$2"
  if grep -q "^${k}=" "$BASE_ENV" 2>/dev/null; then
    sed "s|^${k}=.*|${k}=${v}|" "$BASE_ENV" > "${BASE_ENV}.tmp" && mv "${BASE_ENV}.tmp" "$BASE_ENV"
  else
    echo "${k}=${v}" >> "$BASE_ENV"
  fi
}
if [ -f "$BASE_ENV" ]; then
  # shipped 完整 .env：只覆盖环境专属键，其余 50+ 键（端口/服务名/workers/…）原样保留
  set_env_kv DEER_FLOW_ROOT             "$ROOT"
  set_env_kv BETTER_AUTH_SECRET         "$SECRET"
  set_env_kv DEER_FLOW_TRUSTED_ORIGINS  "$ORIGIN"
  [ -n "$RAGFLOW_API_KEY" ]    && set_env_kv RAGFLOW_API_KEY    "$RAGFLOW_API_KEY"
  [ -n "$RAGFLOW_HTTP_PROXY" ] && set_env_kv RAGFLOW_HTTP_PROXY "$RAGFLOW_HTTP_PROXY"
  [ -n "$LLM_API_KEY" ]        && set_env_kv INTERNAL_LLM_API_KEY "$LLM_API_KEY"
  # DB 密码仅当 deploy.conf 显式给出非默认值才覆盖（默认 agentflow123 已在 shipped .env）
  if [ -n "${DB_PASSWORD:-}" ] && [ "${DB_PASSWORD}" != "agentflow123" ]; then
    set_env_kv POSTGRES_EXT_PASSWORD "$DB_PASSWORD"
    set_env_kv EXTENSIONS_DB_PASSWORD "$DB_PASSWORD"
  fi
  # 云端模型 key（若 conf 提供）
  for k in AGNES_API_KEY ZHIPU_API_KEY DEEPSEEK_API_KEY SILICONFLOW_API_KEY; do
    v="${!k:-}"; [ -n "$v" ] && set_env_kv "$k" "$v"
  done
else
  # 兜底：未找到 shipped .env（异常，正常 offline-export 总会拷入），写最小可用集
  cat > "$BASE_ENV" <<EOF
# Generated by generate-config.sh (fallback: shipped .env not found)
DEER_FLOW_ROOT=${ROOT}
BETTER_AUTH_SECRET=${SECRET}
HOME=/root
PORT=4026
# F.2: gateway 必须用 Docker 服务名连库，否则容器内 localhost 不通。
EXTENSIONS_DB_HOST=postgres-ext
EXTENSIONS_DB_PORT=5432
EXTENSIONS_DB_USER=agentflow
EXTENSIONS_DB_PASSWORD=${DB_PASSWORD}
EXTENSIONS_DB_NAME=agentflow
POSTGRES_EXT_PASSWORD=${DB_PASSWORD}
# F.6: compose 已硬编码网络名，NETWORK_NAME 仅供文档参考，勿取消注释。
DEER_FLOW_TRUSTED_ORIGINS=${ORIGIN}
RAGFLOW_API_KEY=${RAGFLOW_API_KEY}
RAGFLOW_HTTP_PROXY=${RAGFLOW_HTTP_PROXY}
EOF
  for k in AGNES_API_KEY ZHIPU_API_KEY DEEPSEEK_API_KEY SILICONFLOW_API_KEY INTERNAL_LLM_API_KEY; do
    v="${!k:-}"; [ -n "$v" ] && echo "${k}=${v}" >> "$BASE_ENV"
  done
fi

# ── config.yaml：基于包内 shipped 的完整配置注入，绝不覆盖 ──
# EAI-CUSTOM: 旧实现用最小 models-only 文件覆盖 config.yaml，丢了 sandbox 段 →
# gateway AppConfig 校验失败（sandbox Field required）→ crash。改为：offline-export 已把
# deploy/offline/config.yaml（含 sandbox/tools/memory/... 全部段）拷到 $OUT，这里只在其
# models 段首位注入内网 LLM（若有），其余段原样保留。
BASE_CFG="$OUT/config.yaml"
if [ ! -f "$BASE_CFG" ]; then
  echo "ERR: $BASE_CFG 不存在。generate-config 需要包内完整的 config.yaml 作为基础（offline-export 会拷入）。" >&2
  exit 1
fi
if [ -n "$LLM_BASE_URL" ]; then
  if [ -z "$PYTHON" ]; then
    echo "ERR: 需要 python3 把内网 LLM 注入 config.yaml。请安装 python3，或在 deploy.conf 留空 LLM_BASE_URL 用云端默认模型。" >&2
    exit 1
  fi
  # 在首个 'models:' 行后插入 intranet-llm（作为默认/首选模型），保留其它所有段
  "$PYTHON" - "$BASE_CFG" "$LLM_MODEL" "$LLM_API_KEY" "$LLM_BASE_URL" <<'PY' || { echo "ERR: config.yaml 注入失败" >&2; exit 1; }
import sys
path, model, key, base = sys.argv[1:5]
text = open(path, encoding="utf-8").read()
block = ("- name: intranet-llm\n"
         "  display_name: 内网大模型\n"
         "  use: langchain_openai:ChatOpenAI\n"
         f"  model: {model}\n"
         f"  api_key: {key}\n"
         f"  base_url: {base}\n"
         "  request_timeout: 600.0\n  max_retries: 2\n  max_tokens: 8192\n"
         "  temperature: 0.7\n  supports_vision: false\n  supports_thinking: false\n")
marker = "models:\n"
text = text.replace(marker, marker + block, 1) if marker in text else marker + block + "\n" + text
open(path, "w", encoding="utf-8").write(text)
print("  injected intranet-llm as default model (sandbox/tools/memory preserved)")
PY
else
  # 未配内网 LLM：保留 shipped 的完整 config.yaml（含云端模型，内网可连外网时直接用）
  :
fi

# ── extensions_config.json ──
# EAI-CUSTOM: 不覆盖包内已有的 extensions_config.json（含 MCP 服务器配置）。
# offline-export 已把 deploy/offline/extensions_config.json（含 8 个 MCP 服务器）拷到 $OUT。
# 覆盖成空配置会导致 gateway 加载不到任何 MCP 工具（"暂无 MCP 工具"）。只在文件不存在时写空默认。
if [ ! -f "$OUT/extensions_config.json" ]; then
    cat > "$OUT/extensions_config.json" <<'EOF'
{"mcpServers": {}, "skills": {}}
EOF
fi

echo "Generated: $OUT/{.env,config.yaml,extensions_config.json} (brand=${BRAND_NAME})"
