# EAI-CUSTOM: registers EAI extension routers (agents, auth, channel_connections,
# channels, features, feedback, memory, runs, ui) on top of upstream's core router set.
from . import (
    agents,
    artifacts,
    assistants_compat,
    auth,
    browser,
    channel_connections,
    channels,
    features,
    feedback,
    input_polish,
    mcp,
    memory,
    models,
    runs,
    scheduled_tasks,
    skills,
    subagent_batches,
    suggestions,
    thread_runs,
    threads,
    ui,
    uploads,
)

__all__ = [
    "agents",
    "artifacts",
    "assistants_compat",
    "auth",
    "browser",
    "channel_connections",
    "channels",
    "features",
    "feedback",
    "input_polish",
    "mcp",
    "memory",
    "models",
    "runs",
    "scheduled_tasks",
    "skills",
    "subagent_batches",
    "suggestions",
    "threads",
    "thread_runs",
    "ui",
    "uploads",
]
